# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose

services:
  server:
    build:
      context: ./backend
    container_name: Kelet-baranya_backend
    environment:
      NODE_ENV: development
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: kelet_baranya_db
      DB_USER: kelet_user
      DB_PASSWORD: kelet_user
    ports:
      - 3000:3000
    depends_on:
      - mysql
  mysql:
    image: mysql:8.4

    container_name: kelet_barany_mysql

    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kelet_baranya_db
      MYSQL_USER: kelet_user
      MYSQL_PASSWORD: kelet_user

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: kelet_baranya_phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - mysql


volumes:
  mysql_data: